version: '3.8'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana_container
    ports:
      - "3004:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_SECURITY_ALLOW_EMBEDDING=true
    restart: always
    volumes:
      - ./grafana-data:/var/lib/grafana

# not grafana 3000 portunda çalışırsa frontend ile kesişir onu değiştirelim 3003 olabilir 
